version: "3"
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db
